Install fails on Python 2.6
This is due to the use of a dict comprehension which is supported in 2.7 and up only:
```
$ pip install alignment
Downloading/unpacking alignment
  Downloading alignment-1.0.8.tar.gz
  Running setup.py egg_info for package alignment
Installing collected packages: alignment
  Running setup.py install for alignment
    SyntaxError: ('invalid syntax', ('/home/pombredanne/align/lib/python2.6/site-packages/alignment/profile.py', 35, 35, '        return {e: float(w) / t for e
 w in self.__weights.iteritems()}\n'))

Successfully installed alignment
```